---
title: "Coursework and Honors"
---
### Coursework

|Course|Facilitator|
|:------------------------:|:-----------------------:|
|Theoretical Ecology|Dr. Vishwesha Guttal|
|Advanced Ecological Statistics|Dr. Kavita Isvaran|

2. 2018 (IISc - Audited)

|Course|Facilitator|
|:------------------------:|:-----------------------:|
|Quantitative Ecology|Dr. Kavita Isvaran and Dr. Vishwesha Guttal|

3. 2016 - 2018 (Pondicherry University - Coursework)

|Course|Grade|
|:---------------------------------:|:----------------:|
|Conservation Biology|A|
|Remote Sensing and GIS|A+|
|Evolution|A-|
|Environmental Informatics and Spatial Modeling|A+|
|Biodiversity|A+|
|Forest Botany|A|
|Animal Ecology|A|
|Plant Ecology|A+|
|Ecology of Medicinal Plants|A+|
|Ornithology|A|
|Aquatic Ecology|A|
|Terrestrial Ecology|A+|
|Population and Community Ecology|A+|
|Statistics for Ecology and Environmental Sciences|A+|

### Testimonials

1. Ramana Shankar Yenishetti, Senior Project Manager at Ericsson India Global Services (Reporting Manager)

> Preethi joined my team as a fresher for post paid billing project during 2013-14 and worked for 1 - 2 years. She always surprises not only me but entire team with her attitude towards work. She is superb in understanding complex product in no time and ensured output as committed. Being a fresher passed out of college , had no back ground experience but worked like 7 years experienced professional. With no second thoughts i recommend her where ever she work, she will out perform and ensures recognition to the team.

2. Tamanna Kalam, Wildlife Conservationist (Senior at Pondicherry University)

> Preethi, is one of the most hard working and dedicated students I have met till date. Her passion for the field of conservation (despite starting off from a different stream) is contagious! She is extremely diligent in her work and pays close attention to small details. She also puts in a lot of effort to implement feedback/advice given to her. Preethi is always eager to learn something new and is also very supportive of others. She has a long way to go in this field, and with her commendable work ethic, I have no doubt in my mind that she will. She will be an asset to any organisation she joins and I can only wish her the very best of luck.

3. Saravanan Kandavelu, Senior Architect (Team member at Ericsson)

> Preethi is a talented person with quick learning capability. And also she has the capability to adapt to the newer technology in no matter of time. She is an asset to any company that she works for. I am proud to recommend her here.

### Honors

|Award|Organisation|Year|
|:------------------------------------:|:------------------------:|:-------:|
|Best Outgoing Student (Shortlisted)|SSN College of Engineering|2013|
|MENSA High IQ Award|MENSA India|2012|

### Competitive Examinations

1. Graduate Record Examination General Test GRE 2019 - *319.5 out of 346*
2. International English Language Testing System IELTS 2019 - *Band 8.5 out of 9*
3. Graduate Aptitude Test in Engineering GATE 2018 - Ecology and Evolution, *830 out of 1000*, All India Rank : 11
4. UGC-NET Environmental Sciences JRF & LS July 2018 Qualified
5. Test of English as a Foreign Language TOEFL 2012 - *111 out of 120*

### Scholarships

1. Merit scholarship semester 1 to 4 during M.Sc for scoring among the top 3 ranks.
2. University Rank 2 in M.Sc.
3. Merti scholarship year 1 during B.Tech for scoring among the top 3 ranks.
4. University Rank 38 out of 3870 candidates in B.Tech.