---
title: "About me"
---

I am an computer scientist turned ecologist with broad interests in behavioural ecology and animal cognition. 

### Currently

I am a PhD student in Kavita Isvaran's lab at the Indian Institute of Science's [Centre for Ecological Sciences](http://ces.iisc.ac.in/new/). I am studying behavioural variation among individuals and plasticity in the lizard - South Indian Rock Agama (*Psammophillus dorsalis*).

### Academic Background

I did my Masters in Ecology and Environmental Sciences from Pondicherry University. My Masters dissertation was on studying the Factors Affecting Prevalence of *Dendrophthoe falcata* (Loranthaceae) in a Secondary TDEF in Auroville, Pondicherry. I was advised by [Professor N Parthasarathy](http://www.pondiuni.edu.in/profile/dr-n-parthasarathy).

I did my Bachelors in Information Technology from [Sri Sivasubramaniya Nadar College of Engineering](http://www.ssn.edu.in/). My Bachelors dissertation was on simulating a Smarter Toll Gate Based on Web of Things. It was published in IEEE XPlore and presented at IEEE CONECCT 2013 in Bangalore. I was advised by [Professor Vinob Chander](http://www.ssn.edu.in/?page_id=1658) and this was a joint project with [Ragavi Pala Janardhan](https://www.linkedin.com/in/ragavi-pala-janardhan-456b4784/).

### Work Experience

I worked as a research assistant in the Indian Institute of Science's [Centre for Ecological Sciences](http://ces.iisc.ac.in/new/) before starting my PhD.

I worked with [Professor Vishwesha Guttal](https://teelabiisc.wordpress.com/) in the Theoretical Ecology and Evolution Lab under the guidance of [Akanksha Rathore](https://sites.google.com/view/akanksha-rathore/) on lekking dynamics of Blackbuck (*Antilope cervicapra*).

In my other life, I worked in the capacity of a Software Engineer with Zoho Corporation and Ericsson India Global Services Private Limited on implementing POP and IMAP protocols and postpaid billing module development respectively.

### Resume

For my complete resume, please 

<!--click [here](https://drive.google.com/open?id=1eugtdEAlnX-qhvTg077sUm6HDiAzTRls).-->

### Academic Content Writing

I have worked with educators to prepare content for competitive exams and schools. I would be happy to help with writing and designing education material for biology. 